DZ/hotel/urls.py
from django.conf.urls import url

from hotel.views import hotel_list_view
from hotel.views import reserve_list_view
from hotel.views import reserve_hotel
from hotel.views import hotel_info


urlpatterns = [
    url('^reserve/list/$', reserve_list_view, name='reserve_list'),
    url('^reserve/$', reserve_hotel, name='reserve'),
    url('^hotel/(?P<pk>\d+)/$', hotel_info, name='hotel_info'),
    url('^', hotel_list_view, name='main'),
]

DZ/sauth/urls.py
from django.contrib.auth import authenticate
from django.contrib.auth.views import login
from django.conf.urls import url

from sauth.views import register
from sauth.views import logout_handler

urlpatterns = [
    url('^login', login, name='login'),
    # url('^auth', ''),
    url('^logout', logout_handler, name='logout'),
    url('^', register, name='authentication'),
]

DZ/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sauth/', include('sauth.urls')),
    url(r'^', include('hotel.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DZ/hotel/models.py
from django.db import models
from django.utils import timezone

from sauth.models import Client


class Picture(models.Model):
    path = models.FileField(
        verbose_name=u"Фотография",
    )

    class Meta:
        db_table = 'picture'


class Hotel(models.Model):
    name = models.CharField(
        verbose_name=u"Название отеля",
        max_length=255,
    )
    pictures = models.ManyToManyField(
        Picture,
        verbose_name=u"Фотографии отеля",
        db_table='hotel_pictures',
    )
    description = models.TextField(
        verbose_name=u"Описание"
    )

    def __unicode__(self):
        return "<Hotel: {}>".format(self.name)

    class Meta:
        db_table = 'hotel'


class Reserve(models.Model):
    hotel = models.ForeignKey(Hotel)
    client = models.ForeignKey(Client)
    date_start = models.DateTimeField(
        verbose_name=u"Дата начала бронирования",
        default=timezone.now,
    )
    date_end = models.DateTimeField(
        verbose_name=u"Дата окончания бронирования",
        default=timezone.now,
    )
    person_amount = models.PositiveIntegerField(
        verbose_name=u"Кол-во персон",
        default=1,
    )

    class Meta:
        db_table = 'reserve'

DZ/sauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Client(AbstractUser):
    RU_LANG = 'RU'
    EN_LANG = 'EN'
    LANG_CHOICES = (
        (RU_LANG, 'Русский'),
        (EN_LANG, 'English'),
    )
    language = models.CharField(
        verbose_name=u'Язык',
        max_length=16,
        choices=LANG_CHOICES,
        default=RU_LANG,
    )

DZ/hotel/forms.py
from django import forms
from django.forms import widgets

from hotel.models import Reserve


class ReserveCreateForm(forms.ModelForm):

    class Meta:
        model = Reserve
        fields = (
            'date_start',
            'date_end',
            'person_amount',
            'hotel',
            'client',
        )
        widgets = {
            'person_amount': widgets.NumberInput,
            'hotel': widgets.HiddenInput,
            'client': widgets.HiddenInput,
        }

DZ/sauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from sauth.models import Client


class RegisterClient(UserCreationForm):

    class Meta:
        model = Client
        fields = (
            'username',
            'language',
        )


class LoginClient(forms.ModelForm):

    class Meta:
        model = Client
        fields = (
            'username',
            'password',
        )

DZ/hotel/views.py
import datetime
import logging

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render

from hotel.models import Hotel
from hotel.models import Reserve
from hotel.forms import ReserveCreateForm


logger = logging.getLogger(__name__)


def hotel_list_view(request):
    """ Список всех отелей
        Доступна пагинация
    """
    hotels = Hotel.objects.all()[:10]
    # TODO: join list of reserves
    # TODO: pagination
    kw = {
        'object_list': hotels,
        'reserve_form': ReserveCreateForm,
    }
    return render(request, "hotel/object_list.html", kw)


def hotel_info(request, pk):
    """Получение информации об отеле"""
    try:
        obj = Hotel.objects.get(pk=pk)
    except Hotel.DoesNotExist as e:
        logger.info("Hotel not found: {}".format(e))
        obj = None
    kw = {
        'object': obj,
    }
    return render(request, "hotel/hotel_info.html", kw)


def reserve_hotel(request):
    """Резервирование отеля"""
    form = ReserveCreateForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return JsonResponse({
            "success": True,
        })
    else:
        logger.debug('\n'.join(['"{}"={}'.format(k, v) for k, v in request.POST.items()]))
        logger.debug(form.errors)
        return JsonResponse({
            "success": False,
        })

# TODO: форма удаления резерва


@login_required
def reserve_list_view(request):
    """ Список резеров данного юзера
        Доступна пагинация
    """
    today = datetime.datetime.today()
    reserves = Reserve.objects.select_related('hotel').filter(client=request.user, date_end__gte=today)
    kw = {
        'object_list': reserves,
    }
    return render(request, "hotel/reserve_list.html", kw)

DZ/sauth/views.py
from logging import getLogger

from django.shortcuts import render
from django.shortcuts import HttpResponsePermanentRedirect
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.views.decorators.http import require_POST

from sauth.forms import RegisterClient


logger = getLogger(__name__)


def register(request):
    """ Регистрация пользователя или отображение формы регистрации
        * Регистрация работает только для неавторизованных пользователей
        * Если пользователь успешно зарегистрирован, он будет авторизован и редиректен на урл /
    """
    form = RegisterClient(request.POST or None)
    if request.method == "POST" and not request.user.is_authenticated():
        if form.is_valid():
            form.save()
            data = form.cleaned_data
            user = authenticate(username=data['username'], password=data['password1'])
            login(request, user)
            return HttpResponsePermanentRedirect('/')
    kw = {
        "form": form,
    }
    return render(request, "sauth/register.html", kw)


@require_POST
def logout_handler(request):
    """ Логаут пользователя

        :form redirect_to: урл на который сделать редирект после логаута, по умолчанию - текущая страница
    """
    if request.user.is_authenticated():
        logout(request)
    redirect_to = request.POST.get('redirect_to', '/')
    return HttpResponsePermanentRedirect(redirect_to)

DZ/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/main.css' %}" rel="stylesheet">
    {% block extra_css %}
    {% endblock %}
</head>
<body>
<div class="container-fluid">
{% block header %}

    {% if request.user.is_authenticated %}
    <p>Hello, {{ request.user.username }}</p>
    <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <input type="hidden" name="redirect_to" value="{{ request.path }}"/>
        <input type="submit" value="Logout"/>
    </form>

    <div>
        <a href="{% url 'reserve_list' %}">Актуальные резервы</a>
    </div>
    {% else %}
        <a class="btn btn-small btn-default" href="{% url 'login' %}">Login</a>
        <a class="btn btn-small btn-default" href="{% url 'authentication' %}">Register</a>
    {% endif %}

{% endblock %}


{% block body %}
{% endblock %}
</div>
</body>

<script src="{% static '/js/jquery-2.2.4.min.js' %}"></script>
<script src="{% static '/js/jquery.cookie.js' %}"></script>
{% block custom_js %}
{% endblock %}
</html>

DZ/templates/hotel/hotel_info.html
{% extends 'base/base.html' %}

{% load static %}


{% block body %}
<div class="row">
{% if object %}
    Название - {{ object.name }}
{% else %}
    Такого отеля не существует
{% endif %}
</div>
{% endblock %}

DZ/templates/hotel/object_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block body %}

{% for item in object_list %}
    <div class="row" style="border: dashed 1px; margin: 5px; padding: 5px;">
        <a href="{% url 'hotel_info' item.pk %}">
            <h4>{{ item.name }}</h4>
        </a>
        <p>{{ item.description }}</p>
        <!--{% for pic in item.pictures.all %}-->
            <!--<img src="{% get_media_prefix %}{{ pic.path }}" style="max-width: 100px;"/>-->
        <!--{% endfor %}-->
        <form class="form" id="reserve_{{ item.pk }}">
            {{ reserve_form.as_p }}
            <input class="btn btn-small btn-success" type="submit" value="Reserve" onclick="reserve({{ item.pk }})"/>
        </form>
    </div>
{% endfor %}

{% endblock %}


{% block custom_js %}
<script>
var reserve = function(hotel_id) {
    event.preventDefault();
    $.post(
        "{% url 'reserve' %}",
        {
            hotel: hotel_id,
            client: {{ request.user.pk }},
            date_start: $('#reserve_' + hotel_id + ' input#id_date_start').val(),
            date_end: $('#reserve_' + hotel_id + ' input#id_date_end').val(),
            person_amount: $('#reserve_' + hotel_id + ' input#id_person_amount').val(),
            csrfmiddlewaretoken: $.cookie('csrftoken')
        },
        function (result) {
            console.log(result);
        }
    )
}
</script>
{% endblock %}

DZ/templates/hotel/reserve_list.html
{% extends 'base/base.html' %}

{% block body %}
{% for item in object_list %}
    <div>
        <p>Резерв в {{ item.hotel.name }} с {{ item.date_start }} до {{ item.date_end }}</p>
        <p>На {{ item.person_amount }} персон</p>
    </div>
{% endfor %}
{% endblock %}

DZ/templates/sauth/register.html
{% extends 'base/base.html' %}

{% block body %}

<form method="POST" action="{% url 'authentication' %}">
    {% csrf_token %}
    <table>
    {{ form }}
    </table>
    <input type="submit" value="Register"/>
</form>

{% endblock %}